Home work 4 DONE
Alex-Ems/nodejs-homework-rest-api pull request #3
Opened 2023-02-01 04:12 UTC by Alex-Ems

2023-02-01 07:46 UTC, KhYulian requested changes
Потрібні правки

2023-02-01 07:46 UTC, KhYulian commented on controllers/auth/login.js
> +    const passCompare = bcrypt.compareSync(password, user.password);
user.password отримаєте помилку, якщо юзера не знайдено (undefined.password => error)|
Використовуйте optional chaining або зробіть спершу перевірку чи знайдено юзера

2023-02-01 07:46 UTC, KhYulian commented on controllers/auth/login.js
> +        code: 201,
status ,
        code, - непотрібні поля, стосується усього коду

2023-02-01 07:46 UTC, KhYulian commented on controllers/auth/login.js
> +        }
кникайте непотрібної вкладеності. data можна видалити. Стосується усього коду

2023-02-01 13:25 UTC, Alex-Ems commented on controllers/auth/login.js
> +        }
Поняв, поправлю. Робив по відео, і прописував для себе щоб легше було .

2023-02-04 06:55 UTC, KhYulian approved these changes
Чудова робота!

2023-02-04 06:55 UTC, merged